### ISSUE TITLE
MacOS wheels are built for x86_64, not universal2

### ISSUE THREAD

**Issue by lochsh** [OxIonics/common-workflows#27]
Because @cjbe has an M1 Mac, we usually want to build universal2 macos wheels whenever we're building platform-specific wheels.

For `electrode`, we do that with `cibuildwheel`. https://github.com/OxIonics/electrode/blob/master/.github/workflows/package.yml

For `qumo`, we're using the [`package-windows-macos.yml`](https://github.com/OxIonics/common-workflows/blob/master/.github/workflows/package-windows-macos.yml) action from this repo, which doesn't use `cibuildwheel`. I wasn't able to figure out how to build universal2 wheels here.

I tried setting `ARCHFLAGS` env variable as they do in `cibuildwheel` https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/macos.py#L223, but this resulted in build failures during Rust builds for qumo: https://github.com/OxIonics/qumo/runs/8271844845?check_suite_focus=true

It's possible we'd have the same issue if we used `cibuildwheel`. I don't think there's any strong reason not to use `cibuildwheel`, but we'd need to rearrange the pre-build steps as I think cibuildwheel runs in some kind of isolated environment. So we'd need ot provide platform-specific `before-all` settings for installing a rust toolchain instead of using the action we use currently.

**Comment by SquidDev** [comment]
I had a look at this today. As of #28, we can now build universal binaries the binaries, so we can now just use `maturin --universal2` to generate universal Rust `.so`s.

The problem here is on the Poetry side - Poetry [unconditionally generates a platform wheel](https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/masonry/builders/wheel.py#L299-L303), so the resulting wheel has a tag of `macosx_10_15_x86_64` rather than `macosx_10_15_universal2`.

I'm not really sure what the best option is here - something to discuss next Monday perhaps!

**Comment by SquidDev** [comment]
We no longer build wheels for Mac.
